// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Test1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://clubselector-2394a.firebaseapp.com/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("About Gaucho OrganAppZation")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Coders SB");
    driver.findElement(By.cssSelector(".search-btn")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Data Science Club");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("IEEE");
    driver.findElement(By.cssSelector(".search-btn")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("SB Hacks");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("UCSB Crew");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("BFOM");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Gaucho Happy Life");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-box")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Blockchain Club");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Women in SB");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Acapella");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("All-Male");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Music");
    driver.findElement(By.cssSelector(".search-btn")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Hacks");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Inclusive");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("Apple Store");
    driver.findElement(By.cssSelector(".search-btn")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("xuidsafhdsif");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-box")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("poiuyrg");
    driver.findElement(By.cssSelector(".search-btn")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.cssSelector(".search-txt")).click();
    driver.findElement(By.cssSelector(".search-txt")).sendKeys("dhdjfjf");
    driver.findElement(By.cssSelector(".fas")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.linkText("Review")).click();
    driver.findElement(By.linkText("Rate a Club")).click();
    driver.findElement(By.linkText("Search")).click();
    driver.findElement(By.linkText("Home")).click();
  }
}
